<?php
session_start();
if (!isset($_SESSION['usuario'])) {
    // No hay sesión activa, redirigir al inicio de sesión
    header("Location: /PruebaPHP/login");
    exit();
}
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crowny Tech Admin</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

</head>

<body>
    <section class="book bg-danger text-light">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-md-6">
                    <div class="text">
                        <h1>Funciones del Admin para los Items</h1>
                        <a href="" class="btn btn-success">Para las Categorías...</a>
                        <a href="<?= URL_LOGOUT;?>"class="btn btn-primary btn-sm p-3" >Cerrar Sesion</a>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-reservation p-3 bg-light text-dark">

                        <div class="form-group">
                            <h2>Seleccione que quiere hacer con los Items: </h2>
                        </div>

                        <a href="listItems" class="btn btn-primary">Mostrar todos los Items</a>
                        <a href="showInsertItems" class="btn btn-primary">Insertar Item</a>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>


</body>

</html>