<!DOCTYPE html>
<html lang="en">
  <head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Crowny Tech</title>
  <link rel="stylesheet" href="../css/style.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
  <header>
    <div class="content flex_space shadow">
      <div class="logo">
        <img src="./Images/logo.png" alt="">
      </div>
      <a href="/PruebaPHP/" class="btn btn-primary btn-sm p-3 ">Volver a la página de inicio</a>
      <a href="/PruebaPHP/login" class="btn btn-primary btn-sm p-3">Iniciar Sesión</a>
      <a href="<?= URL_LOGOUT;?>"class="btn btn-primary btn-sm p-3" >Cerrar Sesion</a>



    </div>
  </header>

  <section class="home">
    <div class="content">
        <div class="item">
          <img src="./Images/banner.jpg" alt="">
          <div class="text">
            <h1>Lo mejor en tecnología.</h1>
          </div>
        </div>
        
        
      </div>
    </div>
  </section>
  

</body>
</html>