<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crowny Tech Admin</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    
</body>
</html>
<?php
$productData = $data;
?>

<div class="container">
    <a href="admin" class="btn btn-primary mt-4 mb-3">Volver a la zona Admin</a>
    <h1 class="mt-5 mb-4">Tus Productos</h1>
    <div class="table-responsive">
        <table class="table table-bordered table-striped">
            <thead class="thead-dark">
                <tr>
                    <th>Nombre</th>
                    <th>Precio</th>
                    <th>Modelo</th>
                    <th>Categoría</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($productData as $product) : ?>
                    <tr>
                        <td><?= $product->productName; ?></td>
                        <td>$<?= $product->price; ?></td>
                        <td><?= $product->model; ?></td>
                        <td><?= $product->categoryName; ?></td>
                        <td><a href="delete/<?= $product->id_product ?>" class="btn btn-danger">Eliminar</a></td>

                        <td><a href="update/<?= $product->id_product ?>" class="btn btn-success">Editar precio segun la inflacion</a></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

