<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crowny Tech</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
<a href="/PruebaPHP/" class="btn btn-primary btn-sm m-3 p-3">Volver a la página de inicio</a>
    
</body>
</html>
<?php
foreach($prodsDet as $product) {
    $productName = $product->productName;
    $price = $product->price;
    $model = $product->model;
    $weightKG = $product->weightKG;
    $height_cm = $product->height_cm;
    $storageGB = $product->storageGB;
    $id_categoria = $product->id_categoria;
?>

<h1>Detalles del Producto seleccionado</h1>
<table class='table table-bordered table-striped'>
    <thead class='thead-dark'>
        <tr>
            <th>Nombre</th>
            <th>Precio</th>
            <th>Modelo</th>
            <th>Peso</th>
            <th>Altura</th>
            <th>Almacenamiento</th>
            <th>Id categoria</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><?= $productName ?></td>
            <td>$ <?= $price ?></td>
            <td><?= $model ?></td>
            <td>kg <?= $weightKG ?></td>
            <td>cm <?= $height_cm ?></td>
            <td>gb <?= $storageGB ?></td>
            <td><?= $id_categoria ?></td>
        </tr>
    </tbody>
</table>

<?php } ?>
<?php  ?>
