<?php
$producto = $prod;
?>

<h1> Todos nuestros Productos seleccionados </h1>
<table class='table table-bordered table-striped'>
    <thead class='thead-dark'>
        <tr>
            <th>Nombre</th>
            <th>Precio</th>
            <th>Modelo</th>
            <th>Peso</th>
            <th>Altura</th>
            <th>Almacenamiento</th>
            <th>Categoria</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($producto as $product) : ?>
            <tr>
                <td><?= $product->productName ?></td>
                <td>$ <?= $product->price ?></td>
                <td><?= $product->model ?></td>
                <td>kg <?= $product->weightKG ?></td>
                <td>cm <?= $product->height_cm ?></td>
                <td>gb <?= $product->storageGB ?></td>
                <td><?= $product->categoryName ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php require_once './templates/footer.phtml'; ?>
