<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crowny Tech</title>
    <link rel="stylesheet" href="../css/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

</head>

<body>


    <div class="bg-light d-flex justify-content-center align-items-center" style="height: 100vh;">
        <div class="card p-4">
            <form method="POST" action="auth">
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" required class="form-control" id="email" name="email" aria-describedby="emailHelp">
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" required class="form-control" id="password" name="password">
                </div>

                <?php if ($error) : ?>
                    <div class='alert alert-danger' role='alert'>
                        <?= $error ?>
                    </div>
                <?php endif ?>

                <button type="submit" class="btn btn-primary mt-3">Entrar</button>
                <a class="btn btn-secondary mt-3" href="/PruebaPHP/">Volver a inicio</a>
            </form>
        </div>
    </div>



</body>

</html>